### This file animates synthetic trajectories generated in model_generate.py file.

### INPUTS - synthetic_trajs.csv : trajectories generated by the trained GMM model in model_generate.py.
###        - test_input.json : runway, procedural information for test.
###        - animation_filename (used for saving output file.)

### OUTPUT - output/'animation_filename'.html : Do not need to plug in as input.


import numpy as np
import pandas as pd
import time, datetime
import json
import os, argparse

import folium
from folium import plugins
from PIL import Image
import io, requests

from scipy.interpolate import interp1d, PchipInterpolator
import pymap3d as pm


parser = argparse.ArgumentParser()
parser.add_argument("-i", "--input_files", nargs="*", required=True, help='synthetic_trajs.csv, test_input.json animation_filename')
args = parser.parse_args()


# load test_input.json file
with open(args.input_files[1], "r") as f:
    data = json.load(f)


# load synthetic_trajs.csv file
columns = ['t', 'track_id', 'x', 'y', 'z']
df = pd.read_csv(args.input_files[0], names=columns, index_col=False)
all_trajs_id = df.track_id.unique()

syn_trajs = []
for traj_id in all_trajs_id:
    df_traj = df[df.track_id == traj_id]
    df_traj = df_traj.sort_values('t')
    t_smooth = np.arange(df_traj.t.min().astype(int), df_traj.t.max().astype(int)+1)
    
    traj = np.zeros((t_smooth.shape[-1], 4))
    traj[:, 0] = t_smooth
    traj[:, 1] = PchipInterpolator(df_traj.t, df_traj.x)(t_smooth)
    traj[:, 2] = PchipInterpolator(df_traj.t, df_traj.y)(t_smooth)
    traj[:, 3] = PchipInterpolator(df_traj.t, df_traj.z)(t_smooth) 
    syn_trajs.append(traj)


M_TO_NM = 0.000539957
M_TO_FT = 3.28084

min_t = np.min(syn_trajs[0][:,0])
max_t = np.max(syn_trajs[len(syn_trajs)-1][:,0])


# airport, runway configuration
airport_name = data["airport_name"]  #"KJFK"
airport_lat, airport_lon, airport_altitude = data["airport_coordinate"]
# runways_config = data["runways_configuration"]["rwy_names"]
# runways_config_coordinates = data["runways_configuration"]["rwy_coordinates"]


# map, fullscreen, multple layers
m = folium.Map(location=(airport_lat, airport_lon), tiles=None, zoom_start=10)
plugins.Fullscreen(position='topleft', title='FullScreen', title_cancel='Exit',
                   force_separate_button=True).add_to(m)
folium.raster_layers.TileLayer('OpenStreetMap').add_to(m)
folium.raster_layers.TileLayer('Stamen Terrain').add_to(m)
folium.LayerControl().add_to(m)


# airport icon
folium.Marker(location=(airport_lat, airport_lon), popup=airport_name).add_to(m)

# aircraft icon
url = 'https://png.icons8.com/material-outlined/80/000000/airplane-mode-on.png'
image = Image.open(io.BytesIO(requests.get(url).content))
    

t_range = np.arange(min_t, max_t)
points=[]
start_t = datetime.datetime.now()

for t in t_range:
    for i, traj in enumerate(syn_trajs): #for each traj.
        ind = np.where(traj[1:,0]==t)[0]
        
        if ind!=None:
            point = {}
            curr_t = start_t + datetime.timedelta(seconds=t.tolist()-min_t)
            point['time'] = curr_t.strftime('%Y-%m-%dT%H:%M:%S')

            # aircraft icon image with rotating headings
            curr_xEast = traj[ind,1]  #(m)   
            curr_yNorth = traj[ind,2]  #(m)
            curr_zUp = traj[ind,3]/10  #(m)
            curr_lat, curr_lon, curr_alt = pm.enu2geodetic(curr_xEast, curr_yNorth, curr_zUp, airport_lat, airport_lon, airport_altitude)
            curr_alt *= M_TO_FT
            point['coordinates'] = [curr_lon[0], curr_lat[0]]
            
            prev_xEast = traj[ind-1,1]  #(m)   
            prev_yNorth = traj[ind-1,2]  #(m)
            prev_zUp = traj[ind-1,3]/10  #(m)
            prev_lat, prev_lon, prev_alt = pm.enu2geodetic(prev_xEast, prev_yNorth, prev_zUp, airport_lat, airport_lon, airport_altitude)
            prev_alt *= M_TO_FT

            heading = np.arctan2(curr_lat-prev_lat, curr_lon-prev_lon) * 180 / np.pi
            rotated_image = image.rotate(heading)
            rotated_image.save('data/rotated_plane.png')

            icon_url = folium.utilities.image_to_url('data/rotated_plane.png')
            point['icon_url'] = icon_url
            points.append(point)

            
features = [{
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": point['coordinates'],
                    },
                "properties": {
                    "time": point['time'],
                    "id":"plane",
                    'icon':'marker',
                    'iconstyle':{
                        'iconUrl': point['icon_url'],
                        'iconSize': [20, 20]
                        }
                    }
                } for point in points]


plugins.TimestampedGeoJson(
    {
        'type': 'FeatureCollection',
        'features': features
    },
    period='PT10S',
    add_last_point=True,
    auto_play=False,
    loop=False, 
    loop_button=True,
    max_speed=0.1,
    time_slider_drag_update=False,
    duration='PT0S'
).add_to(m)

os.makedirs('output', exist_ok=True)
m.save(args.input_files[2])

